2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Configure stats pid to 30314
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Loading settings from /cephfs/zhanjh/COMP130207/PJ2/wandb/settings
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'PJ2/BiLSTM_CRF_main.py', 'program_abspath': '/cephfs/zhanjh/COMP130207/PJ2/BiLSTM_CRF_main.py', 'program': 'BiLSTM_CRF_main.py'}
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-31 21:27:33,852 INFO    MainThread:30314 [wandb_init.py:_log_setup():520] Logging user logs to /cephfs/zhanjh/COMP130207/PJ2/wandb/run-20240531_212733-gxd0t07e/logs/debug.log
2024-05-31 21:27:33,853 INFO    MainThread:30314 [wandb_init.py:_log_setup():521] Logging internal logs to /cephfs/zhanjh/COMP130207/PJ2/wandb/run-20240531_212733-gxd0t07e/logs/debug-internal.log
2024-05-31 21:27:33,853 INFO    MainThread:30314 [wandb_init.py:init():560] calling init triggers
2024-05-31 21:27:33,853 INFO    MainThread:30314 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {}
2024-05-31 21:27:33,853 INFO    MainThread:30314 [wandb_init.py:init():610] starting backend
2024-05-31 21:27:33,853 INFO    MainThread:30314 [wandb_init.py:init():614] setting up manager
2024-05-31 21:27:33,860 INFO    MainThread:30314 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-31 21:27:33,861 INFO    MainThread:30314 [wandb_init.py:init():622] backend started and connected
2024-05-31 21:27:33,868 INFO    MainThread:30314 [wandb_init.py:init():711] updated telemetry
2024-05-31 21:27:33,886 INFO    MainThread:30314 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-31 21:27:34,974 ERROR   MainThread:30314 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-31 21:27:34,974 ERROR   MainThread:30314 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
  File "/root/miniconda3/envs/ai/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-31 21:27:36,789 WARNING MsgRouterThr:30314 [router.py:message_loop():77] message_loop has been closed
